// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiM1p5_6NhdvG4sgvKF6jKuScyN5gUor0',
    appId: '1:832196899309:web:60340c2258b2ed01be77e4',
    messagingSenderId: '832196899309',
    projectId: 'notification-b59dd',
    authDomain: 'notification-b59dd.firebaseapp.com',
    storageBucket: 'notification-b59dd.appspot.com',
    measurementId: 'G-BJLSMWCLQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC79ZVrKYpPLbp6qEAhpbDsnn4VR1sv97Y',
    appId: '1:832196899309:android:7d9807a3a34a3002be77e4',
    messagingSenderId: '832196899309',
    projectId: 'notification-b59dd',
    storageBucket: 'notification-b59dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsGTSNA31opIUfjVgO2vVZOCSkdEZu2Io',
    appId: '1:832196899309:ios:0d1ed41102724e3fbe77e4',
    messagingSenderId: '832196899309',
    projectId: 'notification-b59dd',
    storageBucket: 'notification-b59dd.appspot.com',
    iosBundleId: 'com.example.receiver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsGTSNA31opIUfjVgO2vVZOCSkdEZu2Io',
    appId: '1:832196899309:ios:22867f6751f3c3bebe77e4',
    messagingSenderId: '832196899309',
    projectId: 'notification-b59dd',
    storageBucket: 'notification-b59dd.appspot.com',
    iosBundleId: 'com.example.receiver.RunnerTests',
  );
}
